# Generated by Django 4.1.1 on 2022-09-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_shippingdetails_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='username',
            new_name='user',
        ),
    ]
