# Generated by Django 4.1.1 on 2022-09-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_username_customers_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={},
        ),
    ]
